package:
    name: "kiwis-pie"
    version: {{ environ['GIT_DESCRIBE_TAG'][1:] }}
build:
    noarch: python
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
source:
  git_url: ../
requirements:
    build:
        - python
        - requests
        - pandas >=0.14.0
        - tabulate
    run:
        - python
        - requests
        - pandas >=0.14.0
        - tabulate
test:
    imports:
        - kiwis_pie
